# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5tErzIoIcxz6Y4l5UmJGzE1lqmnlDWG
"""

!pip install translate

from translate import Translator

# Define the Language Translation Tool
def translate_text():
    # Provide a list of language shortcuts for users
    print("Language Codes Reference:")
    print("English (en), Spanish (es), French (fr), German (de), Chinese (zh), Hindi (hi), Arabic (ar), Russian (ru)")
    print()

    # Get user input
    text_to_translate = input("Enter the text you want to translate: ")
    source_language = input("Enter the source language code (e.g., 'en' for English): ")
    destination_language = input("Enter the destination language code (e.g., 'es' for Spanish): ")

    try:
        # Create a Translator instance
        translator = Translator(from_lang=source_language, to_lang=destination_language)

        # Perform the translation
        translated = translator.translate(text_to_translate)
        print("\nTranslated Text:")
        print(translated)
    except Exception as e:
        print("An error occurred while translating:", str(e))

# Call the function to start the tool
translate_text()